#!/bin/bash
#
# Copyright (C) 2015 GRNET S.A.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


if [ "$SNF_IMAGE_CREATOR_METADATA_OS" != bitnami ]; then
    echo "Quiting... not a bitnami image!" >&2
    exit 0
fi

# Do not force a password change. The password will be locked by
# snf-image-creator and reset by Synnefo during the deployment
rm -f home/bitnami/change-password.sh

# Fix IP address fetching code
if [ -f etc/init.d/welcome ]; then
    sed -i 's/ipaddress=.*/ipaddress=$(ifconfig | grep "inet addr"| awk '"'"'NR==1 {print $2}'"'"' | awk '"'"'BEGIN { FS=":" } { print $2 }'"'"')/' etc/init.d/welcome
fi

if [ -f etc/init/ssh.conf.back ]; then
    mv etc/init/ssh.conf.back etc/init/ssh.conf
fi

if [ -f root/firstboot.sh ]; then
    cat >> root/firstboot.sh <<EOF
export DEBIAN_FRONTEND=noninteractive
/usr/bin/apt-get -y update

# Add Network Manager in the first boot
/usr/bin/apt-get -y install network-manager --no-install-recommends

# Install acpid
/usr/bin/apt-get -y install acpid
echo '/sbin/shutdown -h now "Power button pressed"' > /etc/acpi/powerbtn.sh
EOF
fi

# Create a custom ChangePassword task
mkdir -p root/snf-image/helper
cat >> root/snf-image/helper/overwrite_task_ChangePassword <<EOF
#!/bin/bash

source /usr/share/snf-image-helper/common.sh

set -e

if [ \$1 = post-exec ]; then
    exit 0
fi

if [ -n "\${SNF_IMAGE_PASSWD_HASH+dummy}" ]; then
    warn "Can't handle password hashes"
    exit 101
fi

if [ -z "\${SNF_IMAGE_PASSWD+dummy}" ]; then
    warn "Not running. Password not set"
    exit 101
fi

if [ -f "\$SNF_IMAGE_TARGET/opt/bitnami/scripts/init/functions" ]; then
    if grep vm_get_applications_password "\$SNF_IMAGE_TARGET/opt/bitnami/scripts/init/functions" &>/dev/null; then
        echo -e "\nvm_get_applications_password() {\necho \"\$SNF_IMAGE_PASSWD\"\n}\n" >> "\$SNF_IMAGE_TARGET/opt/bitnami/scripts/init/functions"
    fi

    if grep vm_get_system_password "\$SNF_IMAGE_TARGET/opt/bitnami/scripts/init/functions" &>/dev/null; then
        echo -e "\nvm_get_system_password() {\necho \"\$SNF_IMAGE_PASSWD\"\n}\n" >> "\$SNF_IMAGE_TARGET/opt/bitnami/scripts/init/functions"
    fi
else
    warn "File: \\\`/opt/bitnami/scripts/init/functions' does not exist!"
fi
exit 101
EOF
chmod +x root/snf-image/helper/overwrite_task_ChangePassword

# vim: set sta sts=4 shiftwidth=4 sw=4 et ai :

