#!/bin/bash
#
# Copyright (C) 2015 GRNET S.A.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


if [ "$SNF_IMAGE_CREATOR_METADATA_OS" != bitnami ]; then
    echo "Quiting... not a bitnami image!" >&2
    exit 0
fi

# Add Network Manager in the first boot
echo "apt-get update && apt-get install network-manager --no-install-recommends" >> root/firstboot.sh

# vim: set sta sts=4 shiftwidth=4 sw=4 et ai :

